version: "3.9"
services:
    template-bot:
        build: "."
        image: template-bot:latest
        container_name: template-bot
        volumes:
            - type: bind 
              source: /var/log/bot-test
              target: /usr/src/app/logs
        deploy:
            resources:
                limits:
                    cpus: "0.50"
                    memory: 300M
