version: "3.9"
services:
    ctftime-bot:
        build: "."
        image: ctftime-bot:1.0
        container_name: ctftime-bot
        volumes:
            - type: bind 
              source: /var/log/bot-test
              target: /usr/src/app/logs
        deploy:
            resources:
                limits:
                    cpus: "0.50"
                    memory: 300M
