version: "3"
services:
    template-bot:
        build: "."
        image: template-bot:latest
        container_name: template-bot
        volumes:
            - "/var/log/ctftime-bot:/usr/src/app/logs"
        deploy:
            resources:
                limits:
                    cpus: "0.50"
                    memory: 300M
